name: Trdl releaser
on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Perform kubedog release using trdl server
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: werf/trdl-vault-actions/release@main
        with:
          vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
          project-name: kubedog
          git-tag: ${{ github.event.ref }}
          vault-auth-method: approle
          vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}
